### ISSUE TITLE
Datepicker: Issue when clearing datepicker value 

### ISSUE THREAD

**Issue by sjasaniel** [infor-design/enterprise-ng#1397]
**Describe the bug**
Issue when clearing datepicker value 

**To Reproduce**
Precondition:
1. Update datepicker.demo.html 

```
        <button soho-button (click)="clear_SetEmptyString()">Clear_SetEmptyString</button>

        <button soho-button (click)="clear_SetValue()">Clear_SetValue</button>
```
2) In datepicker.demo.ts add the ff

```
  clear_SetEmptyString() {
    this.model.range2 = ''; 
  }

  clear_SetValue() {
    this.range2?.setValue('', true, true); // this will clear the value of range2 correctly.
  }
```
Steps to replicate:
1) Populate range2 field. (this should be in-range)
2) Clear field using clear_SetEmptyString button  // expectation is that that value will be cleared. actual result: the value retains
3) Clear field using clear_SetValue button // this will clear the value of range2 correctly.

**Version**
- ids-enterprise-ng: 14.1.0-dev

**Additional context**
The issue is in writeValue of soho-datepicker.component.ts. Here's a console error: error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'trim')
TypeError: Cannot read properties of undefined (reading 'trim')
    at SohoDatePickerComponent.writeValue (soho-datepicker.component.ts:589:57)
    at onChange (shared.ts:240:24)
    at form_control.ts:462:29
    at Array.forEach (<anonymous>)
    at FormControl.setValue (form_control.ts:461:26)
    at ng_model.ts:330:20
    at ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (ng_zone.ts:418:29)
    at ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at resolvePromise (zone.js:1213:31)
    at zone.js:1283:17
    at ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (ng_zone.ts:403:29)
    at ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:582:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:21)
    at invokeTask (zone.js:1600:14)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1637:21)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
