### ISSUE TITLE
Error displayed running SohoToolbarFlex unit tests

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#396]
**Describe the bug**

When running the unit tests for the enterprise angular project, several errors are displayed.  These don't stop the tests passing, but suggest there is an issue that needs resolving.

The following code is suspect:

```typescript
onSelected(event) {
    let data = '';
    if (event.item.type === 'actionbutton' || event.item.type === 'menubutton') {
      data = event.item.selectedAnchor[0].dataset.action;
    } else {
      data = event.item.element.dataset.action;
    }
    console.log(data);
  }
```
Specifically:

a) The implicit use of `any` for event which should be `SohoToolbarFlexSelectedEvent`
b) No guard against the event.item being null
c) `selectedAnchor` not existing on the declared `item` types.
d) It is preferable to avoid console.log in unit tests.

**To Reproduce**

```sh
npm prune
npm i
npm run build:lib
npm run test:lib
```

```txt
ERROR: TypeError: Cannot read property 'style' of undefined
TypeError: Cannot read property 'style' of undefined
    at CirclePager.showExpandedView (http://localhost:9876/absoluteC:/git/infor-design/enterprise-ng/node_modules/ids-enterprise/dist/js/sohoxi.js?b9120e34b9e1240a9cb6ac9c305972d3021e1b30:27781:25)
    at CirclePager.unbind (http://localhost:9876/absoluteC:/git/infor-design/enterprise-ng/node_modules/ids-enterprise/dist/js/sohoxi.js?b9120e34b9e1240a9cb6ac9c305972d3021e1b30:27815:12)
    at CirclePager.destroy (http://localhost:9876/absoluteC:/git/infor-design/enterprise-ng/node_modules/ids-enterprise/dist/js/sohoxi.js?b9120e34b9e1240a9cb6ac9c305972d3021e1b30:27841:12)
    at http://localhost:9876/_karma_webpack_/webpack:/src/lib/circlepager/soho-circlepager.component.ts:93:28
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/C:/git/infor-design/enterprise-ng/node_modules/zone.js/dist/zone.js:391:1)
    at ProxyZoneSpec.push.../../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/C:/git/infor-design/enterprise-ng/node_modules/zone.js/dist/zone-testing.js:289:1)
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/C:/git/infor-design/enterprise-ng/node_modules/zone.js/dist/zone.js:390:1)
    at Zone.push.../../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/webpack:/C:/git/infor-design/enterprise-ng/node_modules/zone.js/dist/zone.js:150:1)
    at NgZone.push.../../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (http://localhost:9876/_karma_webpack_/webpack:/C:/git/infor-design/enterprise-ng/node_modules/@angular/core/fesm5/core.js:17257:1)
    at SohoCirclepagerComponent../src/lib/circlepager/soho-circlepager.component.ts.SohoCirclepagerComponent.ngOnDestroy (http://localhost:9876/_karma_webpack_/webpacHeadlessChrome 73.0.3683 (Windows 10.0.0): Executed 57 of 305 SUCCESS (0 secs / 3.702 secs)
```

**Expected behavior**

No error messages (or warnings) displayed in the console.

**Version**
- ids-enterprise-ng: 5.2.1 and master.

**Screenshots**

**Platform**

**Additional context**

**Comment by tmcconechy** [comment]
i did add a safety check for this here https://github.com/infor-design/enterprise/pull/1821/files#diff-b98db4c3512fd71dcfd41451d6fb5481R360 in 4.1.7-beta
