### ISSUE TITLE
Issue when trying to setup with latest code

### ISSUE THREAD

**Issue by mgadde7** [infor-design/enterprise-ng#648]
**Describe the bug**
When we are setting up we are getting issue with chalk as in we have not instantiated it in scripts/version-sync.js

**To Reproduce**
1. Run npm i
2. Run npm run build
`>enterprise-ng-master
> npm run build:lib && npm run build:app

> enterprise-ng-master
> npm run sync:lib && npx ng build ids-enterprise-ng --prod

> enterprise-ng-master
> node ./scripts/version-sync.js

enterprise-ng-master\scripts\version-sync.js:41
  console.log(chalk.red('Error!'), msg, '\n');
              ^

ReferenceError: chalk is not defined
    at logError (enterprise-ng-master\scripts\version-sync.js:41:15)
    at exec (enterprise-ng-master\scripts\version-sync.js:52:7)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ids-enterprise-ng-app@ sync:lib: `node ./scripts/version-sync.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ids-enterprise-ng-app@ sync:lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    *\npm-cache\_logs\2019-10-22T13_28_46_868Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ids-enterprise-ng-app@ build:lib: `npm run sync:lib && npx ng build ids-enterprise-ng --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ids-enterprise-ng-app@ build:lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    *\npm-cache\_logs\2019-10-22T13_28_46_942Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ids-enterprise-ng-app@ build: `npm run build:lib && npm run build:app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ids-enterprise-ng-app@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     *\Roaming\npm-cache\_logs\2019-10-22T13_28_47_035Z-debug.log`
**Expected behavior**

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]
'
Machine:  Windows OS 10

**Comment by tmcconechy** [comment]
@mgadde7 where are you getting this? On your project? Or setting up this repo locally?
I'm not able to reproduce this both using the https://github.com/infor-design/enterprise-ng-quickstart (which i just updated) which would simulate how you would use this.

Im also not able to reproduce this on this repo either.

**Comment by mgadde7** [comment]
I have downloaded the project not cloned it.

I guess node modules have chalk but I did not find it in scripts/version-sync.js

I have added require command to get chalk 
It is fixed
